version: 2
updates:
  - package-ecosystem: pip
    directory: /backend
    versioning-strategy: increase-if-necessary
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
